# Generated by Django 5.2.12 on 2026-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burger',
            name='image',
        ),
        migrations.AddField(
            model_name='burger',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL изображения'),
        ),
    ]
