# Generated by Django 5.2.12 on 2026-04-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Оплата на сайте картой'), ('cash', 'Оплата при получении')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
